naam = input("Voer uw naam in: ")
adres = input("Voer uw adres in: ")
postcode = input("Voer uw postcode in: ")
woonplaats = input("Voer uw woonplaats in: ")

print("\nAdres kaart")
print(40 * "-")
print("|  Naam =", naam   )
print("|  Adres =", adres  )
print("|  postcode=", postcode)
print("|  Woonplaats=", woonplaats)
print(40 * "-")
