OLIEBOL = 0.99
APPELFLAP = 1.45

AANTAL_OLIEBOL = 3
AANTAL_APPELFLAP = 5

OLIEBOL_KOSTEN = OLIEBOL * AANTAL_OLIEBOL
APPELFLAP_KOSTEN = APPELFLAP * AANTAL_APPELFLAP  

TOTAAL = OLIEBOL_KOSTEN + APPELFLAP_KOSTEN

# 3 OELIEBOLLEN EN 5 APPELFLAPPEN KOSTEN IN TOTAAL 10.22

print(f'{AANTAL_OLIEBOL} OELIEBOLLEN EN {AANTAL_APPELFLAP} APPELFLAPPEN KOSTEN IN TOTAAL {TOTAAL}')