naam = input("Voer uw naam in: ")
adres = input("Voer uw adres in: ")
postcode = input("Voer uw postcode in: ")
woonplaats = input("Voer uw woonplaats in: ")

print("\nAdres kaart")
print(40 * "-")
print (f"|  Naam = {naam}")
print(f"|  Adres = {adres} " )
print(f"|  postcode= {postcode}")
print(f"|  Woonplaats= {woonplaats}")
print(40 * "-")
